### ISSUE TITLE
Is defined multiple times

### ISSUE THREAD

**Issue by farzadi** [floatinghotpot/socket.io-unity#1]
I have errors in some of my packages
 

> The type 'Action' exists in both 'SocketIoClientDotNet, Version =1.0.0.0 , Culture=neutral , PublicKeyToken=null' and System.Core, Version =3.5.0, Culture=neutral , PublicKeyToken = b77a5c561934e089'

and 

> The type'Func<Tresult>' exists in both 'System.Core', Version=3.5.0.0 , Culture=neutral,PublicKeyToken = b77a5c56193e089 and 'WebSocket4Net, Version =0.14.1.0 ,Culture=neutral ,PublicKeyToken = ed4e154b696bf72a'

**Comment by alagatar** [comment]
Same problem. Hope soon will be fixed.

**Comment by floatinghotpot** [comment]
It will be helpful if you can provide the version number of:
* Unity
* Mono
* .NET

**Comment by alagatar** [comment]
Last version of unity 2017.1f3, released 11 July 2017

**Comment by farzadi** [comment]
Unity 5.5.1f1
.NET v4.5.x v4.5.x v4.6.x

**Comment by floatinghotpot** [comment]
As I know, you can use .NET v4.5 on Windows/XBOX platform, but to build runtime for cross platform like iOS or Android, you need select Mono and .NET 2.0/3.5.

See:
http://answers.unity3d.com/questions/1305565/as-of-12017-what-is-the-highest-version-of-net-tha.html

**Comment by alagatar** [comment]
This error present in editor and break all work.
With lasterst release of unity you cant use this pluging becouse of error.
Looks like you have same named classes.

**Comment by alagatar** [comment]
Settings
![untitled-1](https://user-images.githubusercontent.com/5358134/28163668-c562d06e-67d4-11e7-94ba-3bd90d8beb54.png)

Errors
error CS0433: The imported type `System.Action' is defined multiple times
error CS0433: The imported type `System.Func<TResult>' is defined multiple times
error CS0433: The imported type `System.Func<T,TResult>' is defined multiple times

**Comment by floatinghotpot** [comment]
Weird, I still did not figure out what happens in your situation. 

It works quite well when I test the demo project with Unity 5.4.4 in my office and Unity 5.6.1 at home.

Or, you may try building the library from source code here (using branch net20):
https://github.com/floatinghotpot/SocketIoClientDotNet/tree/net20

**Comment by floatinghotpot** [comment]
Hi guys, I just downloaded and install Unity 2017.1 (on my iMac), start the test-server/index.js, then open the Demo/Hello.unity in Unity, configure the URL, then run the demo in Unity, it works just fine. See the attached screenshot.

![socketio-demo](https://user-images.githubusercontent.com/2339512/28172357-ebc9db6e-681d-11e7-8dd7-7ae481ffd78e.png)

**Comment by jake** [comment]
Also having this issue, with completely unrelated libraries.

> Assets/ThirdParty/SteamVR/InteractionSystem/Core/Scripts/Util.cs(411,69): error CS0433: The imported type `System.Action' is defined multiple times

Sounds like maybe something in one of these DLLs is writing something to `System.Action`, which is causing unexpected other third party libraries using the same name?

**Comment by farzadi** [comment]
Yes if you just use this package its not have a problem, errors came from when you add other packages to your project

**Comment by alagatar** [comment]
Sample code for receive this issues
```
using System;
using UnityEngine;

public class Test:MonoBehaviour
{
    public Action callback;
    public Func<int> callback2;
    public Func<int, bool> callback3;
}
```

**Comment by gershonatron** [comment]
I am seeing the same System.Action collision issue with a BLE plugin.

**Comment by Oakshiro** [comment]
Same problem here, System.Func<TResult>' is defined multiple times all around

**Comment by tbhyn** [comment]
Encountering this problem with Vuforia. What can we do in such a case?

**Comment by sputn1ck** [comment]
still not fixed, maybe open source your code so we can fix it?

you shouldn't distribute that kind of messy code for 10€

**Comment by floatinghotpot** [comment]
Here is the source code, 
https://github.com/floatinghotpot/SocketIoClientDotNet/tree/net20

If anyone wanna contribute, try forking the code and help to fix it.

**Comment by marius-bughiu** [comment]
Looks like two different packages try to define the same type in the same namespace by either
- having two different dependencies that define the same Namespace.Type
- maybe referring to two different versions of the same dependency

My eyes are on System.Threading.Tasks.Unofficial. It seems to be defining some types for compatibility. If, for example, some other plugin would be using the TaskParallelLibrary - then I could see why these two plugins would probably not work together.

Unfortunately I won't have any time for this until next week.
If it's not solved by then I will have a look.

A sample project on Git to reproduce the issue would help a lot.

**Comment by alex-carlson** [comment]
I'm getting an error in Unity that is probably related to this.

`ArgumentException: An element with the same key already exists in the dictionary.`

It looks like that's being triggered when I try to connect to the server after initially declaring `socket = null;`.  The error doesn't happen if I just do `socket = "http://localhost:3000";` for example.

I'm also running on latest Unity 2017.1.1f1

**Comment by Dr-Jerm** [comment]
Just getting on the "I'm having problems too" train. Here's my output:

`The type 'Func<T1, T2, TResult>' exists in both 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'WebSocket4Net, Version=0.14.1.0, Culture=neutral, PublicKeyToken=eb4e154b696bf72a'`

As stated above, only seems to break in the presence of other packages. In my specific case it's https://github.com/neuecc/UniRx

**Comment by patricknelson** [comment]
Just researching this for now... but: @marius-bughiu - Did you ever get a chance to work on this a bit more?

**Comment by GkhanKINAY** [comment]
I am using **UnityAction** until the problem is solved.
Here is the example usage,

```
using UnityEngine;
using UnityEngine.Events;

public class Test : MonoBehaviour 
{
	private void Start () 
	{
		DemoLog( () => 
		{
			Debug.Log("Second message"); 
		});
	}

	private void DemoLog(UnityAction callback)
	{
		Debug.Log("First message");
		callback();
	}
}

@floatinghotpot, can you fix this ?
https://github.com/floatinghotpot/socket.io-unity/issues/10
Thanks.

**Comment by Vellames** [comment]
Same problem here guys
@GkhanKINAY Thank you for your tip, this saved my day :)

**Comment by siordache94** [comment]
Hi ,
how is using UnityEngine.Events; supposed to fix the issue ? Currently at GGJ , conflicting with STEAMVR
will be waitin for you answer.
Thanks in advance!

**Comment by GkhanKINAY** [comment]
@siordache94 Hi, good luck in GGJ. 
Use "UnityAction" instead of "Action" 
Where is your problem?

**Comment by siordache94** [comment]
it's very deep , if you try to import this and https://www.assetstore.unity3d.com/en/#!/content/32647 this asset, there's conflict on action , i tried putting either unityaction in steamvr , tried wrappin system in sys (in case of conflicting namespace) 
after changing all the references to system.action  i get 40+ other errors.
IF (and thats a big if) there's a quick fix that you know about ( i have little to no experience ) , please do share... 
thank you

**Comment by GkhanKINAY** [comment]
@siordache94 I change Util.cs and now working, i think.
Replace Assets/SteamVR/InteractionSystem/Core/Scripts/Util.cs

[Util.cs.zip](https://github.com/floatinghotpot/socket.io-unity/files/1670337/Util.cs.zip)

**Comment by James-Quigley** [comment]
I'm having the same issue. Unity 2017.3 and .NET 3.5. Replacing System.Action with UnityAction works sometimes, but not always, so it isn't really a valid fix for me. Does anybody have any thoughts as to what might be causing this? I'm new to Unity and C#, so unfortunately I'm pretty clueless

**Comment by patricknelson** [comment]
@GkhanKINAY If you think you've got a viable fix, could you submit a PR and reference this ticket?

**Comment by GkhanKINAY** [comment]
@patricknelson OK, i fixed the problem on the source code. ([https://github.com/floatinghotpot/SocketIoClientDotNet/pull/1](url))

**Comment by floatinghotpot** [comment]
Thanks to @GkhanKINAY , the file has been merged.

**Comment by James-Quigley** [comment]
I'm attempting to use this library alongside Google Poly Toolkit. I'm still running into the System.Action is defined multiple times, even with the new dlls from @GkhanKINAY. Did the issue actually get fixed, or is this potentially an issue with the Poly Toolkit?

**Comment by GkhanKINAY** [comment]
@James-Quigley hmm, i will test in 1-2 hour.

**Comment by GkhanKINAY** [comment]
@James-Quigley Hi again, sorry for delay. I tested and your problem is WebSocket4Net.dll, not SocketIoClientDotNet.dll. (And you need delete Newtonsoft.Json.dll because "Poly Toolkit" project is have one.)

Problem: https://github.com/kerryjiang/WebSocket4Net/blob/master/WebSocket4Net/Action.cs

**Comment by James-Quigley** [comment]
@GkhanKINAY Thanks so much for your help. So the fix is to go into the source for WebSocket4Net and change the Action definition and all its references to something else e.g. CustomAction?

**Comment by GkhanKINAY** [comment]
@James-Quigley Yes, you are right. (I changed "ActionTrigger" instead of "Action" and build:SocketIoClientDotNet.dll)
Look my pull request: https://github.com/floatinghotpot/SocketIoClientDotNet/pull/1

**Comment by Xortrox** [comment]
I have a similar issue where "System.Func" is defined multiple times

Replacing it with other things just causes more errors like ".Contains is not defined, are you missing a using reference" which then suggest System.Linq or Quobject.Collections.Immutable in some classes like "Unity3DRider.cs"

**Comment by siordache94** [comment]
Hi,
the multiple declaration is an issue also with the postprocessing stack and volumetric lighting
can you please wrap this module in a namespace, fixing all possible issues, please?

**Comment by not82** [comment]
Hi , 
Got the same issue here, with Zenject. 

It seams WebSocket4Net got a mscorelib different of .NET 2.0 included in recent versions of Unity.. And Zenject is using it and don't know what reference he must use. ( same package , but 2 different sources )

:/

**Comment by timgoeij** [comment]
Hi

I have the issue where the System.Func<T, TResult> is defined multiple times with the websocket4net dll in combination with the mapbox api. I am using unity2017.2

**Comment by Andychan0704** [comment]
Hi,

Seems the fix only changed "Action fn" to "ActionTrigger fn". (source code in AckImpl.cs or elsewhere)

Believe, others such as

Action <object> fn1;
Action<object, object> fn2;
Action<object, object, object> fn3;

also need to be changed as well.

As I encountered the issue (defined multiple times) for those calls (ie. System.Action<T1>, System.Action<T1,T2>, System.Action<T1,T2,T3>  ... is defined multiple times)

Cheers

**Comment by ahmedsherpiny** [comment]
Hi,

I still have this problem when I uses Fingers - Touch Gestures from AssetStore.

I face it with System,Action<T1,T2,T3>() and System.Func()

Any hints or workarounds?

**Comment by Lesliehdezg** [comment]
same error but with websocket4net.dll 

the error with SocketIoClientDotNet works.

**Comment by IlyaVorozhbit** [comment]
короче, просто нужно взять другой провайдер сокета для юнити и всё

**Comment by farukcan** [comment]
same error with websocket4net.dll : 

Assets/GMES/UTIL/ExpressionParser.cs(303,43): error CS0433: The imported type `System.Func<T,TResult>' is defined multiple times
Assets/GMES/FullSerializer/Source/fsConfig.cs(70,16): error CS0433: The imported type `System.Func<T1,T2,TResult>' is defined multiple times

**Comment by Lesliehdezg** [comment]
Wich new provider recommend?

**Comment by henrikljungberg5467** [comment]
I wanted to use this with IBM Watson SDK (speech-to-text) and got "Is defined multiple times" problem. Also another time I was tryng to use it alongside the Embedded browser asset (https://assetstore.unity.com/packages/tools/gui/embedded-browser-55459) and that gave me loads of "Is defined multiple times" problems.

**Comment by det3d** [comment]
I'm having the same problem trying to use Socket.IO and Hololens in Unity.  
Getting error CS0433 'System.Action<T1,T2>'
Also getting the error for 'System.Func<TResult>'
Not really sure how to fix this.  Tried downloading the Fix above for the SocketIoClientDotNet.dll file, but nothing really changed.  Any help would be great!

**Comment by James-Quigley** [comment]
@det3d I ended up using the BestHTTP Unity library to do Socket.IO stuff on the HoloLens. It worked great! It is paid, but honestly saved me so much headache that it is probably worth it.

**Comment by det3d** [comment]
Thanks for the tip!  Best HTTP worked out great for Socket.IO and Hololens!

**Comment by hypeofpipe** [comment]
It still doesn't work because it is a indus code!

**Comment by JCanovas** [comment]
same error with websocket4net.dll :  
I am using it together with the oculus plugin "Oculus integration" and the error appears in System.Func...Any Solution? Thank you

**Comment by Jezzamonn** [comment]
Hm, running into this too, conflicting with mscorlib:

error CS0433: The type 'Action<T1, T2, T3>' exists in both 'WebSocket4Net, Version=0.14.1.0, Culture=neutral, PublicKeyToken=eb4e154b696bf72a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by gamedev2492** [comment]
No solutions for this???

**Comment by Jezzamonn** [comment]
For me, the issue I had was I was somewhere in my code or a framework I was using, I had my own enum or class that was also called Action, and in the same namespace. I think moving it into a different namespace helped me.

**Comment by OptrixAU** [comment]
The only solution is to go through WebSocket4Net and SuperSocket and replace all of the uses of Func<> and Action<> with proper delegates (Func and Action were classes added in a later version of .NET so they aren't being handled properly by the Unity compiler).

Unity should not be allowing ANY package authors to use either of those in their code - they are only suitable for genuine .NET3.5 and up, and if you're supposed to be .NET 2 compatible they shouldn't be used anywhere. 

I can forgive WebSocket4Net for using it, since it's not really expecting to be used in unity - but TextMeshPro / Unity Package Manage / Oculus Utilities should really know better.

**Comment by OptrixAU** [comment]
Made a new fork of SuperSocket to replace occurrences of **Func** and **Action** with real delegates, which should completely resolve the problem.

**Comment by OptrixAU** [comment]
I upgraded my scripting framework in 2018.4 to .NET 4x, then copied the .NET4 versions of the assemblies over from a freshly checked-out version of WebSocket4Net 1.6.4.

This got rid of most of the problems, which exist because of some .NET 2.0 compatibility tweaks that are happening inside WebSocket4Net. 

Alternatively, you can recompile WebSocket4Net by moving the classes that all of it's dependencies make in System and System.Linq to other namespaces.

**Comment by OptrixAU** [comment]
This link is to .NET 2.0 versions of the libraries for WebSocket4Net that will both work in Unity and won't cause problems with non-2.0 features such as Func, Action and Linq.

https://drive.google.com/drive/folders/1p0MRrFCdbWM4oCNTv_wGvcRQ_PlZpnlP?usp=sharing

**Comment by AlekOstolle** [comment]
Is there a solution, can't still find one ? Should we do something to remove the Func in the package manager, instead of the dll ?

**Comment by OptrixAU** [comment]
The new versions of Unity (2018.4+) allow you to use **.NET Standard 2** and **.NET 4.x** as your scripting backend. This means that you can use the much later versions of your libraries, so that this problem doesn't occur.

Alternatively, you need to do what I did for WebSocket4Net, and go into the code. If you search for the definition of 'func' and rename it to something else, you'll remove the problem. 

It's caused by the fact that quite a few libraries use LINQ-style code techniques, and then define those types (like Action and Func) themselves so that they compile in .NET 2. If you _remove_ those definitions, it should work.

**Comment by AlekOstolle** [comment]
@OptrixAU Sorry, so if I understand you, the WebSocket4Net you uploaded above (23 aug) is already corrected to remove the "func" ? Are the two others dlls in the drive required ?

Since I never edited a dll, i tryied yours and have others errors instead, like:
"C:\Program Files\Unity\Hub\Editor\2019.2.9f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\UI\Core\RectMask2D.cs(197,51): error CS1579: foreach statement cannot operate on variables of type 'HashSet<IClippable>' because 'HashSet<IClippable>' does not contain a public instance definition for 'GetEnumerator'"

May you help me, thx
